### ISSUE TITLE
Automated tests with newer library versions

### ISSUE THREAD

**Issue by amigalemming** [commercialhaskell/stackage-next#1]
Currently, when I import a library that gets an upgrade which is out of the import bounds in one of my packages, I get an e-mail that i need to adapt my package. What about automatically compiling and running tests of my package with new the library version? If the tests succeed, Stackage may even create a pull request with the relaxed import version bounds. This would simplify updating import version bounds a lot.

**Comment by qrilka** [comment]
@amigalemming please post issues about Stackage on [Stackage repo](https://github.com/commercialhaskell/stackage). This one is a temporary test repo. And I'd propose to close this issue.

**Comment by amigalemming** [comment]
Sure, but isn't it buried under lots of dependency resolving issues there?

**Comment by amigalemming** [comment]
I opened this one: https://github.com/commercialhaskell/stackage/issues/4696
